name: Generate 3D Contribution Graph

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do reposit칩rio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clonar reposit칩rio 3D Contrib e gerar gr치fico
        run: |
          git clone https://github.com/yoshi389111/github-profile-3d-contrib.git
          cd github-profile-3d-contrib
          npm install
          node ./index.js --username marlondcury --output ../profile-3d-contrib.svg

      - name: Fazer upload do gr치fico gerado
        uses: actions/upload-artifact@v3
        with:
          name: contribution-graph
          path: ./profile-3d-contrib.svg
