name: Generate 3D Contribution Graph

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        run: |
          npx github-profile-3d-contrib --username marlondcury --output ./profile-3d-contrib.svg
